### ISSUE TITLE
Problem with 1.4vpre crafting 

### ISSUE THREAD

**Issue by frxggo** [BuilderDolphin/dolphSol-Macro#127]
When It tries to craft the gilded coin it misses it by just a little bit and ends up trying to craft for the volcanic device, I havent found a way to fix this yet but if I do I'll let you know and close this issue. Thanks!

**Comment by frxggo** [comment]
I forgot to mention that I'm only having this problem with gilded coin, I dont know if the other crafting options work or not since I dont use them.

**Comment by pochitalover** [comment]
Dolphin added in a new update for the 1.4 pre that it now accurately clicks gilded coin. If it still doesnt work redownload it.

**Comment by frxggo** [comment]
> Dolphin added in a new update for the 1.4 pre that it now accurately clicks gilded coin. If it still doesnt work redownload it.



> Dolphin added in a new update for the 1.4 pre that it now accurately clicks gilded coin. If it still doesnt work redownload it.

alright thanks
