### ISSUE TITLE
macro not working

### ISSUE THREAD

**Issue by pro1212309** [BuilderDolphin/dolphSol-Macro#244]
broke due to era 8 changing the position of the collection button (pls try to fix it as soon as possible) (i don't wanna go broke on potions)

**Comment by fellowbeingcoolhere** [comment]
click collection first, then start macro. (make sure to close chat) (i saved ur life and ur potion lacking your welcome)

**Comment by pro1212309** [comment]
i found another way what u have to do the camera alignment then pause then do it manually then resume
