### ISSUE TITLE
resetting is no longer possible in the new update

### ISSUE THREAD

**Issue by muniscool** [BuilderDolphin/dolphSol-Macro#8]
dolphsol has to be reworked because as of the new update resetting is no longer possible.

**Comment by NotInstinct** [comment]
Was going to say the same thing since reseting is big on this macro and we can no longer reset after the update.

**Comment by pew1048** [comment]
they need to rework like go back to the spawn, or automatically rejoining the game

**Comment by muniscool** [comment]
new dolphsol version released
